### ISSUE TITLE
Release separately or merge changes?

### ISSUE THREAD

**Issue by andrewwhitehead** [sicpa-dlab/peer-did-python#39]
I have another branch of this repo (https://github.com/andrewwhitehead/peer-did-python/tree/upd/pydid) with several changes: 

- Using `pydid` for the DID Document representation
- Adding `@context` entries to resolved DID Documents
- Using the spec-recommended 8-character verification method identifier
- Adding `authentication`, `assertionMethod`, `capabilityInvocation`, and `capabilityDelegation` entries to DID Documents for authentication keys (consistent with did:key)
- Disallowing `=` in peer DIDs (base64url-encoded service should never be padded)

Is there any interest in merging this changes, or should I look at releasing this library separately?

@dbluhm

**Comment by dbluhm** [comment]
I'm very interested in these changes. While working on side projects using this library, the overabundance of types have been giving me a lot of heartburn. cc @victormartinez-work @chumbert

**Comment by chumbert** [comment]
There's definitely interest in merging your changes here, feel free to open a PR and we'll see that they're merged and released.
