### ISSUE TITLE
peerdid.core not included in published package?

### ISSUE THREAD

**Issue by dbluhm** [sicpa-dlab/peer-did-python#43]
I tried using peerdid but am running into the following error on import:

```
.venv/lib/python3.10/site-packages/peerdid/__init__.py:3: in <module>
    from . import core, dids, errors, keys
.venv/lib/python3.10/site-packages/peerdid/dids.py:9: in <module>
    from .core.peer_did_helper import (
E   ModuleNotFoundError: No module named 'peerdid.core'
```

When checking my site-packages directory, I found that only the following files were downloaded from PyPI:
```
dids.py  errors.py  __init__.py  keys.py 
```

Is there perhaps an issue with the setup of the package? Or is my local environment somehow getting corrupted? I wiped my virtual environment and reinstalled dependencies but that resulted in the same error.

cc @chumbert

**Comment by chumbert** [comment]
Sorry to hear that. I'll investigate and release a fix ASAP.

**Comment by Tanzi005** [comment]
Is it solved? I am having the same problem :(

**Comment by dbluhm** [comment]
@Tanzi005 Yes, this fix was included as of version 0.5.2

**Comment by Tanzi005** [comment]
I am trying to run the repo 'didcomm-demo-python' but was unable to run the following imports : 

from peerdid import peer_did
from peerdid.core.did_doc_types import DIDCommServicePeerDID
from peerdid.did_doc import DIDDocPeerDID
from peerdid.types import VerificationMaterialFormatPeerDID, VerificationMaterialAgreement, \
    VerificationMethodTypeAgreement, VerificationMaterialAuthentication, VerificationMethodTypeAuthentication

Could you please take a look? Thanks a lot!

**Comment by dbluhm** [comment]
Please open an issue on the didcomm-demo repo. I don't think the demo has been kept up to date. I am unfortunately unable to provide assistance on updating the demo.
